language: ruby

gemfile:
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.2.gemfile
- gemfiles/rails_5.0.6.gemfile
- gemfiles/rails_5.0.7.gemfile
- gemfiles/rails_5.1.4.gemfile
- gemfiles/rails_5.1.5.gemfile
- gemfiles/rails_5.2.gemfile

rvm:
- 2.3.8
- 2.4.5
- 2.5.3
- 2.6.1
- jruby-9.2.5.0

matrix:
  exclude:
  - rvm: 2.4.5
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.5.3
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.6.1
    gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
  - rvm: jruby-9.2.5.0

jdk:
- openjdk10

bundler_args: --without development

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
